### ISSUE TITLE
Just something we need to know

### ISSUE THREAD

**Issue by Icelandjack** [Icelandjack/deriving-via#6]
Does it go like this

```haskell
deriving via (T a) instance C a (X b) --> deriving via (forall a. T a) instance (forall b. C a (X b))

deriving via (T c) instance C a (X b) --> deriving via (forall c. T c) instance (forall a b. C a (X b))
```

or `deriving via (forall a b. T a) instance C a (X b)`

**Comment by RyanGlScott** [comment]
The former is correct. GHC would only quantify type variables at the `via` type that actually appear in the `via` type itself.

Note that while you technically can write the latter `deriving via (forall a b. T a) instance C a (X b)`, it's not what GHC would default to if you had just written `deriving via (T a) instance C a (X b)`.

That being said, there's something a bit odd with GHC's treatment of nested `forall`s at the moment with `StandaloneDeriving`. See https://github.com/RyanGlScott/ghc/issues/31.
